<a href="https://colab.research.google.com/github/Rajithlahiru/-PyTorch-Garbage-Classification-/blob/main/PyTorch_fundamentals_00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **This is a New Beginning of learning PyTorch**

In [55]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu118


**Creating** **a** **tensor**

scalar

In [56]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [57]:
scalar.ndim

0

In [58]:
scalar.item()

7

vector

In [59]:
vector = torch.tensor([2,2])
vector

tensor([2, 2])

In [60]:
scalar.ndim

0

In [61]:
vector.shape

torch.Size([2])

MATRIX

In [62]:
MATRIX = torch.tensor([[2,3],
                       [3,4]])
MATRIX

tensor([[2, 3],
        [3, 4]])

In [63]:
MATRIX.shape

torch.Size([2, 2])

In [64]:
MATRIX.ndim

2

In [65]:
MATRIX[0]

tensor([2, 3])

In [66]:
MATRIX[1]

tensor([3, 4])

TENSOR

In [67]:
TENSOR = torch.tensor([[[1,2,3],
                        [2,3,4],
                        [1,2,6]]])
TENSOR

tensor([[[1, 2, 3],
         [2, 3, 4],
         [1, 2, 6]]])

In [68]:
TENSOR.shape

torch.Size([1, 3, 3])

## Random Tensors

In [69]:
# create a random tensor with size of (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.6482, 0.8555, 0.2244, 0.3782],
        [0.5039, 0.5304, 0.4248, 0.8209],
        [0.8646, 0.5126, 0.2693, 0.3416]])

In [70]:
random_tensor.ndim

2

In [71]:
# creating similar shape random tensor to image
random_image_tensor = torch.rand(size=(244,244,3))#height, width and color channel #RGB
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([244, 244, 3]), 3)

## Zeros and Ones

In [72]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [73]:
random_tensor

tensor([[0.6482, 0.8555, 0.2244, 0.3782],
        [0.5039, 0.5304, 0.4248, 0.8209],
        [0.8646, 0.5126, 0.2693, 0.3416]])

In [74]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [77]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [78]:
ones.dtype

torch.float32

## Aranging tensors

In [80]:
one_to_ten = torch.arange(start=0, end=11, step= 2)
one_to_ten

tensor([ 0,  2,  4,  6,  8, 10])

## Dealing with tensor data types

Tensors Datatype is a one of the big 3 errors you will run into pyTorch and Deeplearning


*   Tensors are not right data type
*   Tensors are not in right shape
*   Tensors are not in right devices





In [83]:
# Float32 datatype
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype= None,
                               device=None,
                               requires_grad=False) # whether gradient track or not
float_32_tensor

tensor([3., 6., 9.])

In [84]:
#when there is a issue with tensor datatypes
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [86]:
float_32_tensor

tensor([3., 6., 9.])